/**
 * Test Credentials Configuration
 *
 * This file contains test credentials for development and testing purposes.
 * IMPORTANT: These credentials should NEVER be used in production.
 *
 * Usage:
 * 1. Import this file in your auth screens
 * 2. Use the test credentials for quick testing
 * 3. Remove or comment out in production builds
 */

export interface TestCredentials {
  mobileNumber: string;
  businessName: string;
  ownerName: string;
  businessType: string;
  gstNumber?: string;
  otp?: string;
}

export interface TestUser {
  id: number;
  mobileNumber: string;
  businessName: string;
  ownerName: string;
  businessType: string;
  planType: string;
  profileComplete: boolean;
}

// Test Credentials for Development
export const TEST_CREDENTIALS: TestCredentials[] = [
  {
    mobileNumber: '9876543210',
    businessName: 'Test Business Solutions',
    ownerName: 'John Doe',
    businessType: 'Proprietorship',
    gstNumber: '22AAAAA0000A1Z5',
    otp: '123456', // This will be generated by backend
  },
  {
    mobileNumber: '9876543211',
    businessName: 'Demo Company Ltd',
    ownerName: 'Jane Smith',
    businessType: 'Private Limited',
    gstNumber: '27BBBBB0000B1Z5',
    otp: '123456',
  },
  {
    mobileNumber: '9876543212',
    businessName: 'Sample Enterprise',
    ownerName: 'Mike Johnson',
    businessType: 'Partnership',
    gstNumber: '33CCCCC0000C1Z5',
    otp: '123456',
  },
  {
    mobileNumber: '9876543213',
    businessName: 'Quick Test Corp',
    ownerName: 'Sarah Wilson',
    businessType: 'LLP',
    gstNumber: '11DDDDD0000D1Z5',
    otp: '123456',
  },
  {
    mobileNumber: '9876543214',
    businessName: 'Dev Business',
    ownerName: 'Alex Brown',
    businessType: 'Manufacturing',
    gstNumber: '44EEEEE0000E1Z5',
    otp: '123456',
  },
];

// Test Users for Login (already registered)
export const TEST_USERS: TestUser[] = [
  {
    id: 1,
    mobileNumber: '9876543210',
    businessName: 'Test Business Solutions',
    ownerName: 'John Doe',
    businessType: 'Proprietorship',
    planType: 'free',
    profileComplete: true,
  },
  {
    id: 2,
    mobileNumber: '9876543211',
    businessName: 'Demo Company Ltd',
    ownerName: 'Jane Smith',
    businessType: 'Private Limited',
    planType: 'starter',
    profileComplete: true,
  },
  {
    id: 3,
    mobileNumber: '9876543212',
    businessName: 'Sample Enterprise',
    ownerName: 'Mike Johnson',
    businessType: 'Partnership',
    planType: 'professional',
    profileComplete: false,
  },
];

// Quick Access Functions
export const getTestCredentials = (index: number = 0): TestCredentials => {
  return TEST_CREDENTIALS[index] || TEST_CREDENTIALS[0];
};

export const getTestUser = (index: number = 0): TestUser => {
  return TEST_USERS[index] || TEST_USERS[0];
};

export const getRandomTestCredentials = (): TestCredentials => {
  const randomIndex = Math.floor(Math.random() * TEST_CREDENTIALS.length);
  return TEST_CREDENTIALS[randomIndex];
};

export const getRandomTestUser = (): TestUser => {
  const randomIndex = Math.floor(Math.random() * TEST_USERS.length);
  return TEST_USERS[randomIndex];
};

// Test OTP Generator (for development only)
export const generateTestOTP = (): string => {
  // Generate a random 6-digit OTP
  return Math.floor(100000 + Math.random() * 900000).toString();
};

// Test Data for Different Scenarios
export const TEST_SCENARIOS = {
  // New user registration
  newUser: {
    mobileNumber: '9876543299',
    businessName: 'New Test Business',
    ownerName: 'New User',
    businessType: 'Proprietorship',
    gstNumber: '99ZZZZZ0000Z1Z5',
  },

  // Existing user login
  existingUser: {
    mobileNumber: '9876543210',
    businessName: 'Test Business Solutions',
    ownerName: 'John Doe',
  },

  // User with incomplete profile
  incompleteProfile: {
    mobileNumber: '9876543212',
    businessName: 'Sample Enterprise',
    ownerName: 'Mike Johnson',
  },

  // Premium user
  premiumUser: {
    mobileNumber: '9876543211',
    businessName: 'Demo Company Ltd',
    ownerName: 'Jane Smith',
  },
};

// Validation Functions
export const validateTestCredentials = (
  credentials: TestCredentials,
): boolean => {
  return !!(
    credentials.mobileNumber &&
    credentials.businessName &&
    credentials.ownerName &&
    credentials.businessType &&
    credentials.mobileNumber.length === 10
  );
};

export const validateTestUser = (user: TestUser): boolean => {
  return !!(
    user.id &&
    user.mobileNumber &&
    user.businessName &&
    user.ownerName &&
    user.businessType
  );
};

// Export default for easy import
export default {
  TEST_CREDENTIALS,
  TEST_USERS,
  TEST_SCENARIOS,
  getTestCredentials,
  getTestUser,
  getRandomTestCredentials,
  getRandomTestUser,
  generateTestOTP,
  validateTestCredentials,
  validateTestUser,
};
